config/routes.rb
DnDoR::Application.routes.draw do
  get "combat/initiative", as: 'initiative'

  resources :encounters
  resources :characters, :only => [:index, :destroy]
  resources :non_player_characters, :except => [:index, :destroy]
  resources :insider_data do
    get :fetch, on: :collection
  end

  root to: 'characters#index'
end

app/models/encounter.rb
class Encounter
  include MongoMapper::Document

  key :name, String
  key :npc_counts, Hash

  def npcs
    NonPlayerCharacter.where(id: npc_counts.select{|_,v| v.to_i != 0}.keys)
  end

  def explain_npcs
    npcs.map do |npc|
      "#{count_of(npc)}x #{npc.name}"
    end * "\n"
  end

  def count_of(npc)
    npc_counts[npc.id.to_s].to_i
  end

  def roll_initiative
    npcs.inject(Hash.new) do |hash, npc|
      hash.merge npc.name => npc.roll_initiative
    end
  end

  def total_xp
    npcs.reduce(0) do |total, npc|
      npc.xp_value.to_i * npc_counts[npc.id.to_s].to_i + total
    end
  end

  def split_xp(split)
    # splits the total xp and rounds the result by 5 (17 -> 15, 21 -> 20)
    splitted = (total_xp / split)
    return splitted - splitted % 5
  end
end

app/controllers/encounters_controller.rb
class EncountersController < ApplicationController
  # GET /encounters
  # GET /encounters.json
  def index
    @encounters = Encounter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @encounters }
    end
  end

  # GET /encounters/1
  # GET /encounters/1.json
  def show
    @encounter = Encounter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @encounter }
    end
  end

  # GET /encounters/new
  # GET /encounters/new.json
  def new
    @encounter = Encounter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @encounter }
    end
  end

  # GET /encounters/1/edit
  def edit
    @encounter = Encounter.find(params[:id])
  end

  # POST /encounters
  # POST /encounters.json
  def create
    @encounter = Encounter.new(params[:encounter])

    respond_to do |format|
      if @encounter.save
        format.html { redirect_to @encounter, notice: 'Encounter was successfully created.' }
        format.json { render json: @encounter, status: :created, location: @encounter }
      else
        format.html { render action: "new" }
        format.json { render json: @encounter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /encounters/1
  # PUT /encounters/1.json
  def update
    @encounter = Encounter.find(params[:id])

    respond_to do |format|
      if @encounter.update_attributes(params[:encounter])
        format.html { redirect_to @encounter, notice: 'Encounter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @encounter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /encounters/1
  # DELETE /encounters/1.json
  def destroy
    @encounter = Encounter.find(params[:id])
    @encounter.destroy

    respond_to do |format|
      format.html { redirect_to encounters_url }
      format.json { head :no_content }
    end
  end
end

app/views/encounters/_form.html.erb
<%= simple_form_for @encounter, html: {class: "form-horizontal"} do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>

    <% NonPlayerCharacter.all.each do |npc| %>
      <div class="control-group">
        <%= label_tag "encounter[npc_counts][#{npc.id}]", npc.name,
          class: 'control-label' %>
        <div class="controls">
          <%= number_field_tag "encounter[npc_counts][#{npc.id}]",
            @encounter.count_of(npc) %>
        </div>
      </div>
    <% end -%>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn-primary" %>
  </div>
<% end %>

app/views/encounters/edit.html.erb
<h1>Editing encounter</h1>

<%= render 'form' %>

<%= link_to 'Show', @encounter %> |
<%= link_to 'Back', encounters_path %>

app/views/encounters/index.html.erb
<h1>
  Encounters
  <%= link_to 'New encounter', new_encounter_path, class: "btn" %>
</h1>

<ul id="encounters-list" class="cf">
  <% @encounters.each do |encounter| %>
    <li>
      <div class="name"><%= encounter.name %></div>
      <div class="npcs"><%= simple_format encounter.explain_npcs %></div>
      <div class="actions">
        <%= link_to 'Show', encounter, class: "btn" %>
        <%= link_to 'Edit', edit_encounter_path(encounter), class: "btn" %>
        <%= link_to 'Destroy', encounter, confirm: 'Are you sure?',
          method: :delete, class: "btn btn-danger" %>
        <%= link_to 'Roll initiative',
          initiative_path(:encounter_id => encounter.id),
          class: "btn btn-warning" %>
      </div>
    </li>
  <% end %>
</ul>

app/views/encounters/new.html.erb
<h1>New encounter</h1>

<%= render 'form' %>

<%= link_to 'Back', encounters_path %>

app/views/encounters/show.html.erb
<p id="notice"><%= notice %></p>

<h2> <%= @encounter.name %> </h2>

<div class="characters">
  <% @encounter.npcs.each do |npc| %>
    <% if @encounter.count_of(npc) > 0 %>
      <div class="character card">
        <div class="count"> <%= @encounter.count_of(npc) %>&times; </div>
        <%= render "non_player_characters/npc_card", :npc => npc %>
      </div>
    <% end -%>
  <% end -%>
</div>

<div class="form-actions" style='clear:both'>
  <%= link_to 'Back', encounters_path, class: "btn" %>
  <%= link_to 'Edit', edit_encounter_path(@encounter), class: "btn" %>
  <%= link_to 'Delete', @encounter, method: "delete", confirm: "Are you sure?",
    class: 'btn btn-danger' %>
  <%= link_to 'Roll initiative', initiative_path(:encounter_id => @encounter.id),
    class: "btn btn-warning" %>
</div>