config/routes.rb
DnDoR::Application.routes.draw do
  get "combat/initiative", as: 'initiative'

  resources :encounters
  resources :characters, :only => [:index, :destroy]
  resources :non_player_characters, :except => [:index, :destroy]
  resources :insider_data do
    get :fetch, on: :collection
  end

  root to: 'characters#index'
end

app/models/character.rb
class Character
  include MongoMapper::Document
  include DiceRolls

  key :name, String
  validates_presence_of :name

  key :level, Integer, default: 1
  validates_presence_of :level

  key :alignment, String

  key :size, String
  validates_presence_of :size

  key :description, String

  key :strength,     AbilityScore, default: 10
  key :constitution, AbilityScore, default: 10
  key :dexterity,    AbilityScore, default: 10
  key :intelligence, AbilityScore, default: 10
  key :wisdom,       AbilityScore, default: 10
  key :charisma,     AbilityScore, default: 10

  key :health_points, Integer
  key :armor_class, Integer
  key :speed, Integer

  key :languages, Array

  key :senses, Array

  def level_bonus
    level.to_i / 2
  end

  def bloodied_hp
    health_points.to_i / 2
  end

  # ability and skill checks
  def check(ability_or_skill)
    ability = (SKILLS[ability_or_skill] or ability_or_skill)

    self.send(ability).modifier + level_bonus
  end

  def fortitude
    10 + AbilityScore.new([strength.to_i, constitution.to_i].max).modifier
  end

  def reflex
    10 + AbilityScore.new([dexterity.to_i, intelligence.to_i].max).modifier
  end

  def will
    10 + AbilityScore.new([wisdom.to_i, charisma.to_i].max).modifier
  end

  def roll_initiative
    D(20) + check(:initiative)
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @characters }
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :no_content }
    end
  end
end

app/views/characters/index.html.erb
<h1>
  Characters
  <%= link_to 'New NPC', new_non_player_character_path, :class => "btn" %>
</h1>

<% @characters.each do |character| %>
  <div class="character card">
    <% if character.is_a?(NonPlayerCharacter) %>
      <%= render "non_player_characters/npc_card", :npc => character %>

      <div class="actions">
        <%= link_to 'Show', character, class: "btn" %>
        <%= link_to 'Edit', edit_non_player_character_path(character),
          class: "btn" %>
        <%= link_to 'Destroy', character_path(character),
          confirm: 'Are you sure?', method: :delete, class: "btn-danger btn" %>
      </div>
    <% else -%>
      <%# Not implemented yet %>
      <%= debug character %>
    <% end -%>
  </div>
<% end %>