config/routes.rb
DnDoR::Application.routes.draw do
  get "combat/initiative", as: 'initiative'

  resources :encounters
  resources :characters, :only => [:index, :destroy]
  resources :non_player_characters, :except => [:index, :destroy]
  resources :insider_data do
    get :fetch, on: :collection
  end

  root to: 'characters#index'
end

app/models/non_player_character.rb
class NonPlayerCharacter < Character
  key :character_roles, Array

  key :xp_value, Integer

  key :custom_fortitude,   Integer
  key :custom_reflex,      Integer
  key :custom_will,        Integer

  key :custom_initiative,  Integer

  def fortitude
    custom_fortitude ? custom_fortitude : super
  end

  def fortitude=(integer)
    self.custom_fortitude = integer
  end

  def reflex
    custom_reflex ? custom_reflex : super
  end

  def reflex=(integer)
    self.custom_reflex = integer
  end

  def will
    custom_will ? custom_will : super
  end

  def will=(integer)
    self.custom_will = integer
  end

  def check(ability_or_skill)
    return custom_initiative if ability_or_skill == :initiative && custom_initiative

    super(ability_or_skill)
  end

  def character_role
    primary = ROLES & character_roles
    secondary = SUB_ROLES & character_roles

    role = primary.to_a * ' '
    role << " (#{secondary.to_a * ' '})" if secondary.any?

    role
  end
end

app/controllers/non_player_characters_controller.rb
class NonPlayerCharactersController < ApplicationController
  # GET /non_player_characters/1
  # GET /non_player_characters/1.json
  def show
    @non_player_character = NonPlayerCharacter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @non_player_character }
    end
  end

  # GET /non_player_characters/new
  # GET /non_player_characters/new.json
  def new
    @non_player_character = NonPlayerCharacter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @non_player_character }
    end
  end

  # GET /non_player_characters/1/edit
  def edit
    @non_player_character = NonPlayerCharacter.find(params[:id])
  end

  # POST /non_player_characters
  # POST /non_player_characters.json
  def create
    @non_player_character = NonPlayerCharacter.new(params[:non_player_character])

    respond_to do |format|
      if @non_player_character.save
        format.html { redirect_to @non_player_character, notice: 'Non player character was successfully created.' }
        format.json { render json: @non_player_character, status: :created, location: @non_player_character }
      else
        format.html { render action: "new" }
        format.json { render json: @non_player_character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /non_player_characters/1
  # PUT /non_player_characters/1.json
  def update
    @non_player_character = NonPlayerCharacter.find(params[:id])

    respond_to do |format|
      if @non_player_character.update_attributes(params[:non_player_character])
        format.html { redirect_to @non_player_character, notice: 'Non player character was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @non_player_character.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/views/non_player_characters/_form.html.erb
<%= simple_form_for @non_player_character,
      html: {class: "form-horizontal"} do |f| %>

  <% if f.error_notification %>
    <div class="alert alert-error fade in">
      <a class="close" data-dismiss="alert" href="#">&times;</a>
      <%= f.error_notification %>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.input :level %>
  <%= f.input :character_roles, collection: ROLES + SUB_ROLES,
    input_html: {class: "chzn-select", multiple: true} %>

  <%= f.input :size, collection: SIZES,
    input_html: {class: "chzn-select"} %>

  <%= f.input :description %>
  <%= f.input :xp_value %>

  <%= f.input :health_points %>
  <%= f.input :armor_class %>
  <%= f.input :custom_fortitude %>
  <%= f.input :custom_reflex %>
  <%= f.input :custom_will %>
  <%= f.input :custom_initiative %>
  <%= f.input :speed %>
  <%= f.input :senses, collection: SENSES,
    input_html: {class: "chzn-select", multiple: true} %>

  <%= f.input :strength %>
  <%= f.input :constitution %>
  <%= f.input :dexterity %>
  <%= f.input :intelligence %>
  <%= f.input :wisdom %>
  <%= f.input :charisma %>

  <%= f.input :alignment, collection: ALIGNMENTS,
    input_html: {class: "chzn-select"} %>
  <%= f.input :languages, collection: LANGUAGES,
    input_html: {class: "chzn-select", multiple: true} %>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary' %>
  </div>
<% end %>

app/views/non_player_characters/_npc_card.html.erb
<table class="npc-card">
  <thead>
    <tr> <th colspan="3">
      <span class="name"><%= npc.name %></span>
      <span class="level-and-role">
        Level
        <%= npc.level %>
        <%= npc.character_role %>
      </span>
    </th> </tr>

    <tr> <th colspan="3">
      <span class="description">
        <%= npc.size %>
        <%= npc.description %>
      </span>
      <span class="xp-value">
        XP
        <%= npc.xp_value %>
      </span>
    </th> </tr>
  </thead>

  <tbody class="combat-stats">
    <tr>
      <td colspan="2">
        <strong>HP</strong> <%= npc.health_points %>;
        <strong>Bloodied</strong> <%= npc.bloodied_hp %>
      </td>
      <td class="to-the-right">
        <strong>Initiative</strong>
        <%= "%+d" % npc.check(:initiative) %>
      </td>
    </tr>

    <tr>
      <td colspan="2">
        <strong>AC</strong> <%= npc.armor_class %>,
        <strong>Fortitude</strong> <%= npc.fortitude %>,
        <strong>Reflex</strong> <%= npc.reflex %>,
        <strong>Will</strong> <%= npc.will %>
      </td>
      <td class="to-the-right">
        <strong>Perception</strong>
        <%= "%+d" % npc.check(:perception) %>
      </td>
    </tr>

    <tr>
      <td colspan="2">
        <strong>Speed</strong> <%= npc.speed %>
      </td>
      <td class="to-the-right">
        <%= npc.senses.reject(&:blank?) * ", " %>
      </td>
    </tr>
  </tbody>

  <tbody class="ability-scores">
    <tr>
      <td>
        <strong>Str</strong>
        <%= npc.strength %>
        (<%= "%+d" % npc.check(:strength) %>)
      </td>
      <td>
        <strong>Dex</strong>
        <%= npc.dexterity %>
        (<%= "%+d" % npc.check(:dexterity) %>)
      </td>
      <td>
        <strong>Wis</strong>
        <%= npc.wisdom %>
        (<%= "%+d" % npc.check(:wisdom) %>)
      </td>
    </tr>

    <tr>
      <td>
        <strong>Con</strong>
        <%= npc.constitution %>
        (<%= "%+d" % npc.check(:constitution) %>)
      </td>
      <td>
        <strong>Int</strong>
        <%= npc.intelligence %>
        (<%= "%+d" % npc.check(:intelligence) %>)
      </td>
      <td>
        <strong>Cha</strong>
        <%= npc.charisma %>
        (<%= "%+d" % npc.check(:charisma) %>)
      </td>
    </tr>
  </tbody>

  <tbody class="more-info">
    <tr>
      <td>
        <strong>Alignment</strong>
        <%= npc.alignment %>
      </td>

      <td colspan="2">
        <strong>Languages</strong>
        <%= npc.languages.reject(&:blank?) * ", " %>
      </td>
    </tr>
  </tbody>
</table>

app/views/non_player_characters/edit.html.erb
<h1>Editing NPC</h1>

<%= render 'form' %>

<%= link_to 'Show', @non_player_character %> |
<%= link_to 'Back', characters_path %>

app/views/non_player_characters/new.html.erb
<h1>New NPC</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/non_player_characters/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'npc_card', :npc => @non_player_character %>

<div class="form-actions">
  <%= link_to "Back", characters_path, class: 'btn'  %>
  <%= link_to "Edit", edit_non_player_character_path(@non_player_character),
        class: 'btn' %>
  <%= link_to "Delete", character_path(@non_player_character),
        method: "delete", confirm: "Are you sure?", class: 'btn btn-danger' %>
</div>