config/routes.rb
DnDoR::Application.routes.draw do
  get "combat/initiative", as: 'initiative'

  resources :encounters
  resources :characters, :only => [:index, :destroy]
  resources :non_player_characters, :except => [:index, :destroy]
  resources :insider_data do
    get :fetch, on: :collection
  end

  root to: 'characters#index'
end

app/views/layouts/_fork_me.html.erb
<a href="https://github.com/vrinek/Dungeons-and-Dragons-on-Rails" id="fork-me">
  <img src="https://s3.amazonaws.com/github/ribbons/forkme_right_white_ffffff.png" alt="Fork me on GitHub">
</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1.0, width=device-width,
      user-scalable=0, maximum-scale=1.0" />
    <title> Dungeons and Dragons on Rails </title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <nav>
      <%= link_to "Encounters", encounters_path %>
      <%= link_to "Characters", characters_path %>
      <%= link_to "Initiative", initiative_path %>
      <%= link_to "D&D Insider Data", insider_data_path %>
    </nav>

    <%= render "layouts/fork_me" %>

    <div id="page">
      <%= yield %>
    </div>
  </body>
</html>